{% set name = "microsoft-kiota-serialization-form" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_serialization_form-{{ version }}.tar.gz
  sha256: 663ece0cb1a41fe9ddfc9195aa3f15f219e14d2a1ee51e98c53ad8d795b2785d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.2,<4
    - pip
  run:
    - python
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - pendulum >=3.0.0

test:
  imports:
    - kiota_serialization_form
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-serialization-form-python
  summary: Implementation of Kiota Serialization Interfaces for URI-Form encoded serialization
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-serialization-form-python
  doc_url: https://github.com/microsoft/kiota-serialization-form-python/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48409
    reason: Dependenccy for msgraph-sdk
    recipe-maintainers:
      - ianaobi
